# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-01 05:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=70)),
                ('logo', models.ImageField(upload_to='Logo')),
                ('ubicacion', models.TextField()),
                ('RTN', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('descuento', models.FloatField()),
                ('subtotal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('celular', models.CharField(max_length=9)),
                ('telcasa', models.CharField(max_length=9)),
                ('correo', models.EmailField(max_length=254)),
                ('fechanacimiento', models.DateTimeField()),
                ('fechacontratacion', models.DateTimeField()),
                ('titulo', models.CharField(max_length=75)),
                ('estado', models.BooleanField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Empleado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Usuarios de Empleado',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=50)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadocivil', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=5)),
                ('ancho', models.FloatField()),
                ('largo', models.FloatField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalAsignado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechapago', models.DateField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Empleado')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Local')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('existencia', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fechaelaboracion', models.DateField()),
                ('fechaVencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identidad', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('celular', models.CharField(max_length=9, null=True)),
                ('telcasa', models.CharField(max_length=9, null=True)),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('fechanacimiento', models.DateTimeField()),
                ('estadocivil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.EstadoCivil')),
            ],
        ),
        migrations.CreateModel(
            name='PagoConsulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Empleado')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='PagoLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('localasignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.LocalAsignado')),
            ],
        ),
        migrations.CreateModel(
            name='Preescripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(max_length=50)),
                ('tiempo', models.CharField(max_length=50)),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Diagnostico')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('celular', models.CharField(max_length=9, null=True)),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('empresa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='VentaMedicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Empleado')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Paciente')),
            ],
        ),
        migrations.AddField(
            model_name='proveedor',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Sexo'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='profesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Profesion'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Sexo'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Proveedor'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='estadocivil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.EstadoCivil'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Sexo'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Empleado'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Paciente'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Medicamento'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='ventamedicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.VentaMedicamento'),
        ),
    ]
