# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-06 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_auto_20180802_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagolocal',
            name='local',
        ),
        migrations.DeleteModel(
            name='PagoLocal',
        ),
    ]
