# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-07 05:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinica', '0004_auto_20180806_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleadousuario',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='empleadousuario',
            name='user',
        ),
        migrations.AddField(
            model_name='empleado',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='EmpleadoUsuario',
        ),
    ]
