# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-07 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_auto_20180806_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preescripcion',
            name='medicamento',
        ),
        migrations.AddField(
            model_name='preescripcion',
            name='medicamento',
            field=models.ManyToManyField(to='clinica.Medicamento'),
        ),
    ]
