# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-10 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0008_auto_20180807_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='subtotal',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
