# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-10 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0009_auto_20180809_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventamedicamento',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
