# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-10 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0011_remove_detalleventa_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventamedicamento',
            name='estado',
        ),
    ]
